---
env:
  browser: true
  es2021: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:promise/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    jsx: true
  tsconfigRootDir: '.'
  project: ['./tsconfig.json']
settings:
  react:
    version: '17'
rules:
  no-await-in-loop: warn
  no-extra-parens: off
  '@typescript-eslint/no-extra-parens': error
  no-sparse-arrays: warn
  no-template-curly-in-string: warn
  require-atomic-updates: warn
  accessor-pairs: off
  array-callback-return: warn
  block-scoped-var: error
  class-methods-use-this: error
  complexity: [warn, { max: 10 }]
  # consistent-return: error # Not necessary due to typescript
  curly: [error, all]
  # default-case: warn # Not necessary due to typescript
  dot-location: [error, property]
  dot-notation: off
  '@typescript-eslint/dot-notation': error
  eqeqeq: [error, smart]
  guard-for-in: warn
  max-classes-per-file: off
  no-alert: error
  no-caller: error
  no-div-regex: off
  no-else-return: off
  no-empty-function: off
  '@typescript-eslint/no-empty-function': off
  no-eq-null: off
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: warn # Revise
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: off
  '@typescript-eslint/no-implied-eval': error
  no-invalid-this: off
  '@typescript-eslint/no-invalid-this': warn
  no-iterator: error
  no-labels: error # Revise
  no-lone-blocks: error
  no-loop-func: off
  '@typescript-eslint/no-loop-func': warn
  no-magic-numbers: off
  '@typescript-eslint/no-magic-numbers': [warn, { ignore: [2, 1, 0, -1, 100, 200, 300, 400, 500, 600, 700, 800, 900], enforceConst: true }]
  no-multi-spaces: error
  no-multi-str: off
  no-new: warn
  no-new-func: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: [error, { props: true }] # Promote pure code
  no-proto: error
  no-restricted-properties: off
  no-return-assign: warn
  no-return-await: off
  '@typescript-eslint/return-await': error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: off
  '@typescript-eslint/no-throw-literal': error
  no-unmodified-loop-condition: warn
  no-unused-expressions: off
  '@typescript-eslint/no-unused-expressions': error
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars': error
  no-useless-call: error
  no-useless-catch: error
  no-useless-concat: error
  no-useless-return: error
  no-void: error
  no-warning-comments: warn
  no-with: error
  prefer-named-capture-group: error
  prefer-promise-reject-errors: error
  radix: error
  require-await: off
  '@typescript-eslint/require-await': warn
  require-unicode-regexp: error
  vars-on-top: off
  wrap-iife: warn
  yoda: error
  strict: [error, never]
  init-declarations: off
  '@typescript-eslint/init-declarations': off
  no-label-var: error
  no-restricted-globals: off
  no-shadow: off
  '@typescript-eslint/no-shadow': warn
  no-undef-init: error
  no-undefined: off
  # no-use-before-define: error # Disable for https://github.com/typescript-eslint/typescript-eslint/issues/2540
  callback-return: error
  global-require: error
  handle-callback-err: warn
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-restricted-modules: off
  no-sync: warn
  array-bracket-newline: [error, consistent]
  array-bracket-spacing: [error, never]
  array-element-newline: [error, consistent]
  block-spacing: [error, always]
  brace-style: off
  '@typescript-eslint/brace-style': [error, 1tbs]
  camelcase: error
  capitalized-comments: off
  comma-dangle: off
  '@typescript-eslint/comma-dangle': [error, always-multiline]
  comma-spacing: off
  '@typescript-eslint/comma-spacing': [error, { before: false, after: true }]
  comma-style: [error, last]
  computed-property-spacing: [error, never]
  consistent-this: [error, that]
  eol-last: [error, always]
  func-call-spacing: off
  '@typescript-eslint/func-call-spacing': [error, never]
  func-name-matching: [error, always]
  func-names: off
  func-style: [error, expression]
  function-paren-newline: off # Turned off because it has issues with arrow functions
  id-blacklist: off
  id-length: off
  id-match: off
  implicit-arrow-linebreak: off
  indent: off
  '@typescript-eslint/indent': [error, tab, { SwitchCase: 1 }]
  jsx-quotes: [error, prefer-double]
  key-spacing: [error, { beforeColon: false, afterColon: true, mode: strict}]
  keyword-spacing: off
  '@typescript-eslint/keyword-spacing': [error, { before: true, after: true }]
  line-comment-position: off
  linebreak-style: [error, unix]
  lines-around-comment: [error, { beforeBlockComment: true, allowBlockStart: true, allowObjectStart: true, allowArrayStart: true, allowClassStart: true }]
  lines-between-class-members: off
  '@typescript-eslint/lines-between-class-members': [error, always]
  max-depth: [warn, 4]
  max-len: [warn, { code: 200 }]
  max-lines: [warn, 600]
  max-lines-per-function: off
  max-nested-callbacks: off
  max-params: [warn, 8]
  max-statements: [warn, { max: 10 }]
  max-statements-per-line: [error, { max: 1 }]
  multiline-comment-style: off
  multiline-ternary: [error, always-multiline]
  new-cap: off
  new-parens: error
  newline-per-chained-call: [error, { ignoreChainWithDepth: 3 }]
  no-array-constructor: off
  '@typescript-eslint/no-array-constructor': error
  no-bitwise: error
  no-continue: off
  no-inline-comments: off
  no-lonely-if: error
  no-mixed-operators: off
  no-mixed-spaces-and-tabs: [error, smart-tabs]
  no-multi-assign: error
  no-multiple-empty-lines: error
  no-negated-condition: off
  no-nested-ternary: off
  no-new-object: error
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: off
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: off
  object-curly-newline: [error, { consistent: true }]
  object-curly-spacing: off
  '@typescript-eslint/object-curly-spacing': [error, always]
  object-property-newline: [error, { allowAllPropertiesOnSameLine: true }]
  one-var: [error, never] # { initialized: never }
  one-var-declaration-per-line: off
  operator-assignment: [error, always]
  operator-linebreak: [error, before, { overrides: { '=': after } }]
  padded-blocks: [error, never]
  padding-line-between-statements:
    - error
    - { blankLine: always, prev: [cjs-import, import], next: '*' }
    - { blankLine: always, prev: '*', next: [cjs-import, import] }
    - { blankLine: any, prev: [cjs-import, import], next: [cjs-import, import] }
    - { blankLine: always, prev: [const, let, var], next: '*' }
    - { blankLine: always, prev: '*', next: [const, let, var] }
    - { blankLine: any, prev: [const, let, var], next: [const, let, var] }
    - { blankLine: always, prev: '*', next: return }
    - { blankLine: always, prev: return, next: '*' }
    - { blankLine: always, prev: '*', next: 'block-like' }
    - { blankLine: always, prev: 'block-like', next: '*' }
  prefer-object-spread: error
  quote-props: off # [error, consistent-as-needed]
  quotes: off
  '@typescript-eslint/quotes': [error, single, { avoidEscape: true, allowTemplateLiterals: true }]
  semi: off
  '@typescript-eslint/semi': [error, never]
  semi-spacing: [error, { before: false, after: true }]
  semi-style: [error, last]
  sort-keys: off
  sort-vars: off
  space-before-blocks: [error, always]
  space-before-function-paren: off
  '@typescript-eslint/space-before-function-paren': [error, { anonymous: always, named: never, asyncArrow: always }]
  space-in-parens: [error, never]
  space-infix-ops: off
  '@typescript-eslint/space-infix-ops': error
  space-unary-ops: [error, { words: true, nonwords: false }]
  spaced-comment: off # TODO: Not when writing ts directive [error, always]
  switch-colon-spacing: [error, { before: false, after: true }]
  template-tag-spacing: [error, never]
  unicode-bom: [error, never]
  wrap-regex: off
  arrow-body-style: off
  arrow-parens: off
  arrow-spacing: [error, { before: true, after: true }]
  generator-star-spacing: [error, { before: false, after: true }]
  no-confusing-arrow: off
  no-duplicate-imports: off
  '@typescript-eslint/no-duplicate-imports': error
  no-restricted-imports: off
  no-useless-computed-key: error
  no-useless-constructor: off
  '@typescript-eslint/no-useless-constructor': error
  no-useless-rename: error
  no-var: error
  object-shorthand: warn
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: off
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  rest-spread-spacing: [error, never]
  sort-imports: off
  symbol-description: off
  template-curly-spacing: [error, never]
  yield-star-spacing: [error, { before: false, after: true }]
  grouped-accessor-pairs: [error, getBeforeSet]
  no-console: error
  no-constructor-return: warn
  no-loss-of-precision: off
  '@typescript-eslint/no-loss-of-precision': warn
  no-nonoctal-decimal-escape: error
  no-promise-executor-return: error
  no-unreachable-loop: error
  no-unsafe-optional-chaining: warn
  no-use-before-define: off
  '@typescript-eslint/no-use-before-define': error
  no-useless-backreference: error
  prefer-exponentiation-operator: error
  prefer-regex-literals: error
  id-denylist: [error, data]
  consistent-return: off
  default-case: off
  default-case-last: off
  default-param-last: off
  '@typescript-eslint/default-param-last': off
  function-call-argument-newline: off
  no-restricted-exports: off

  '@typescript-eslint/adjacent-overload-signatures': off
  '@typescript-eslint/array-type': [error, array]
  '@typescript-eslint/await-thenable': error
  '@typescript-eslint/ban-ts-comment': error
  '@typescript-eslint/ban-tslint-comment': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/class-literal-property-style': off
  '@typescript-eslint/consistent-indexed-object-style': off
  '@typescript-eslint/consistent-type-assertions': [error, { assertionStyle: 'as', objectLiteralTypeAssertions: 'never' }]
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/member-delimiter-style': [error, { multiline: { delimiter: none }, singleline: { delimiter: comma, requireLast: false } }]
  '@typescript-eslint/member-ordering': off
  '@typescript-eslint/method-signature-style': error
  '@typescript-eslint/naming-convention': error
  '@typescript-eslint/no-base-to-string': error
  '@typescript-eslint/no-confusing-non-null-assertion': warn
  '@typescript-eslint/no-confusing-void-expression': [error, { ignoreArrowShorthand: true }]
  '@typescript-eslint/no-dynamic-delete': error
  '@typescript-eslint/no-empty-interface': error
  '@typescript-eslint/no-explicit-any': error
  '@typescript-eslint/no-extra-non-null-assertion': error
  '@typescript-eslint/no-extraneous-class': error
  '@typescript-eslint/no-floating-promises': error
  '@typescript-eslint/no-for-in-array': error
  '@typescript-eslint/no-implicit-any-catch': error
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-invalid-void-type': off
  '@typescript-eslint/no-misused-new': error
  '@typescript-eslint/no-misused-promises': error
  '@typescript-eslint/no-namespace': error
  '@typescript-eslint/no-non-null-asserted-optional-chain': error
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-parameter-properties': off
  '@typescript-eslint/no-require-imports': error
  '@typescript-eslint/no-this-alias': warn
  '@typescript-eslint/no-type-alias': off
  '@typescript-eslint/no-unnecessary-boolean-literal-compare': true
  '@typescript-eslint/no-unnecessary-condition': true
  '@typescript-eslint/no-unnecessary-qualifier': warn
  '@typescript-eslint/no-unnecessary-type-arguments': error
  '@typescript-eslint/no-unnecessary-type-assertion': error
  '@typescript-eslint/no-unnecessary-type-constraint': error
  '@typescript-eslint/no-unsafe-argument': error
  '@typescript-eslint/no-unsafe-assignment': error
  '@typescript-eslint/no-unsafe-call': error
  '@typescript-eslint/no-unsafe-member-access': error
  '@typescript-eslint/no-unsafe-return': error
  '@typescript-eslint/no-var-requires': error
  '@typescript-eslint/non-nullable-type-assertion-style': error
  '@typescript-eslint/prefer-as-const': error
  '@typescript-eslint/prefer-enum-initializers': off
  '@typescript-eslint/prefer-for-of': error
  '@typescript-eslint/prefer-function-type': error
  '@typescript-eslint/prefer-includes': error
  '@typescript-eslint/prefer-literal-enum-member': warn
  '@typescript-eslint/prefer-namespace-keyword': off
  '@typescript-eslint/prefer-nullish-coalescing': error
  '@typescript-eslint/prefer-optional-chain': error
  '@typescript-eslint/prefer-readonly': error
  '@typescript-eslint/prefer-readonly-parameter-types': error
  '@typescript-eslint/prefer-reduce-type-parameter': error
  '@typescript-eslint/prefer-regexp-exec': error
  '@typescript-eslint/prefer-string-starts-ends-with': error
  '@typescript-eslint/prefer-ts-expect-error': error
  '@typescript-eslint/promise-function-async': off
  '@typescript-eslint/require-array-sort-compare': warn
  '@typescript-eslint/restrict-plus-operands': warn
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/sort-type-union-intersection-members': off
  '@typescript-eslint/strict-boolean-expressions': error
  '@typescript-eslint/switch-exhaustiveness-check': error
  '@typescript-eslint/triple-slash-reference': [error, { path: never, types: never, lib: never }]
  '@typescript-eslint/type-annotation-spacing': error
  '@typescript-eslint/typedef': off
  '@typescript-eslint/unbound-method': warn
  '@typescript-eslint/unified-signatures': error
  '@typescript-eslint/no-dupe-class-members': error
  '@typescript-eslint/no-redeclare': error


  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-uses-react: off
  react/display-name: off
